### ISSUE TITLE
Homebrew-fontsへの登録

### ISSUE THREAD

**Issue by zchee** [tomokuni/Myrica#1]
Ricty nextとしていま話題になっていますMyrica、Homebrew-fontsへの登録を許可していただきたくissue立てさせて頂きました。

[Homebrew](https://github.com/Homebrew/homebrew)
[Homebrew-fonts](https://github.com/caskroom/homebrew-fonts)

ご存知でしたら大変申し訳ありませんが、念のためHomebrewについて簡単に説明させて頂きますと、任意のURLからファイルをダウンロード、ビルド、インストールまでを自動化すべく作られたruby製のMac専用パッケージマネージャーです。
Windowsのchocolatey、Ubuntuのapt-get、CentOSのyumと同じものとして考えて頂いてよろしいかと思います。
Homebrew-fontsは、主にバイナリインストール向けのHomebrewを拡張し、フォントの自動インストールに対応させたものになります。

開発段階である、またはHomebrewへの登録が不本意、などの理由があれば見送らせていただきます。issueをクローズして頂いて構いません。

また、許可していただける際には、ダウンロードURLは
https://github.com/tomokuni/Myrica/archive/master.zip
https://github.com/tomokuni/Myrica/raw/master/Myrica.7z
のどちらが好ましいでしょうか？

よろしくお願いいたします。

**Comment by tomokuni** [comment]
ご連絡ありがとうございました。
こっそりと公開していたので、「話題になっている」？ことに、驚いています。
再配布等に制限はありませんので、Homebrew-fontsへの登録はご自由に頂いて結構です。

ダウンロードURLは、どちらでも構いませんが、フォントを使用する方向けには、
https://github.com/tomokuni/Myrica/raw/master/Myrica.7z
として、サイズを小さくしていますので、こちらが扱いやすいかと思います。

**Comment by zchee** [comment]
少なくとも自分のtwitterのタイムラインでは話題沸騰でした。
あとは、Starの付き方の早さが物語っていそうです。

許可して頂きありがとうございました。
早速登録しておきます。

Homebrew-cask自体が7zをサポートしているか未確認でしたので、確認後、どちらかを登録させて頂きます。
登録した時点でissueはcloseさせて頂きます。
またご連絡致します。

**Comment by zchee** [comment]
https://github.com/caskroom/homebrew-fonts/pull/304

**Comment by tomokuni** [comment]
もう遅いかもしれませんが、ZIP圧縮ファイルも登録するようにしました。
使いやすいものをご使用頂ければと思います。

**Comment by zchee** [comment]
無事Mergeされました。
ZIPファイルの件、改めて後ほどcommitしてみます。
