### ISSUE TITLE
descent が正

### ISSUE THREAD

**Issue by haccy** [tomokuni/Myrica#3]
http://fontforge.github.io/ja/fontinfo.html#TTF-Metrics
などによると、
- font.os2_typodescent
- font.hhea_descent

は負数であるべきところ、正の数が設定されるようになっている

**Comment by tomokuni** [comment]
負数を指定しているつもりでしたが、ご指摘のように正の数が設定されていました。
ソースを確認したところ、定数として負数を指定していましたが、font.os2_typodescent、font.hhea_descent を設定する箇所で、-1を掛けており、結果として正数になっていました。（お恥ずかしい。。）
次バージョンにて修正いたします。
ご指摘ありがとうございました。
