### ISSUE TITLE
バージョン表記

### ISSUE THREAD

**Issue by bwv998** [tomokuni/Myrica#4]
はじめまして。
Myrica、愛用させてもらっています。

細かい報告で申し訳ないのですが、フォントプレビューの画面に表示されるバージョンが「 2.007.20150313 」になっているようです。
(ファイル右クリック  -> 「プロパティ」 -> 「詳細」のバージョン表記は「2.008.20151210」です。)

ご確認よろしくお願いします。

環境 : Windows 7 Pro 64bit

**Comment by tomokuni** [comment]
「2.008.20151210」はインストールしましたでしょうか？（ファイル右クリック->「インストール」）
ここらへんのWindowsの動作仕様が不明確なのですが、インストールせずにプレビュー画面を開いた場合には、現在インストールされているバージョンが表示されるのだと思います。
（過去にこのような経験があり、インストールを行うと解消されました。）
お手数ですが、試して頂けますか？

**Comment by bwv998** [comment]
おっしゃるとおり、インストールした後にプレビューしたところ、バージョンの表記が更新されていることを確認しました。
こういう仕様になっているんですね。
確認不足で失礼しました。

これからもMyrica使わせていただきます。
ありがとうございました。
