### ISSUE TITLE
TeraTermで下線が表示されない

### ISSUE THREAD

**Issue by yutkat** [tomokuni/Myrica#5]
MyricaMをWindowsで使っていますが、TeraTermで下線（アンダーライン）が表示されませんでした。

- Myrica
![myrica](https://user-images.githubusercontent.com/8683947/34455600-90b3a920-edc5-11e7-81c4-c55997d69ac4.PNG)

- MSゴシック
![ms_gothic](https://user-images.githubusercontent.com/8683947/34455599-908a804a-edc5-11e7-8086-9c258f939e09.PNG)

MSゴシック以外のフォントRicty、Rounded M+、Cicaでも下線は表示されました。

**Comment by yutkat** [comment]
フォントを再インストールしたところ正常にアンダーラインが表示されるようになりましたのでクローズします。

**Comment by yutkat** [comment]
やっぱり解決してなかったようです。（解決したと思っていたのはWindowsのフォント反映がうまくできていないことが原因）


すこし追いかけてみたところ、たぶん解決方法を見つけたのでご確認ください。

https://github.com/tomokuni/Myrica/blob/b737107723bfddd917210f979ccc32ab3eb6dc20/Source/myricaM_generator.py#L243
```python
font.upos = 45
```

参考:
https://github.com/miiton/Cica/blob/9c801eb367ec5e2597c6f854c0676e8a667a8e7b/cica.py#L471

**Comment by tomokuni** [comment]
ご連絡ありがとうございます。
また、解決策のご提示、ありがとうございます。
現象がTeraTermで発生することと、ご提示頂いた解決策を適用することで、現象が解決することを確認しました。
「font.upos = 45」が何を意味するのかは分かっていませんが、2.012.20180119 として更新しましたので、productフォルダの圧縮ファイルを使用して yutakatayさん の環境でもご確認頂けますでしょうか？

**Comment by yutkat** [comment]
確認しました。直ったみたいです！
ご対応ありがとうございました。

![fix](https://user-images.githubusercontent.com/8683947/35157805-756d1daa-fd78-11e7-98c0-3dc0a85b29f3.PNG)
